name: scanner_3d_pro
description: Professional 3D Scanning Solution
publish_to: "none" # Empêche la publication accidentelle sur pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

  # Design et style
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.0

  # Fonctionnalités
  dio: ^5.0.0
  provider: ^6.0.0
  path_provider: ^2.0.11
  supabase_flutter: ^1.10.25
  shared_preferences: ^2.1.0
  network_info_plus: ^4.0.0
  model_viewer_plus: ^1.0.5
  file_picker: ^10.2.0
  uuid: ^4.0.0
  share_plus: ^7.0.2
  clipboard: ^0.1.3
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/html/viewer.html

dependency_overrides:
  sign_in_with_apple: ^7.0.1
